### ISSUE TITLE
Path to WebInspector not correct on 12.5.1?

### ISSUE THREAD

**Issue by mozfreddyb** [zwo/patch_webinspect#2]
Looks like the path mentioned in the readme is not correct.
Here's what's actually in /System/Library/PrivateFrameworks/WebInspector.framework/Versions/A:

> 
> % ls -l
> total 0
> drwxr-xr-x  43 root  wheel  1376 11 Aug 08:44 Resources
> drwxr-xr-x   3 root  wheel    96 11 Aug 08:44 _CodeSignature
> % ls -l _CodeSignature
> total 8
> -rw-r--r--  4418 root  wheel  747 11 Aug 08:44 CodeResources
> % ls -l Resources
> total 16
> -rw-r--r--  1 root  wheel  1370 11 Aug 08:44 Info.plist
> drwxr-xr-x  3 root  wheel    96 11 Aug 08:44 ar.lproj
> drwxr-xr-x  3 root  wheel    96 11 Aug 08:44 ca.lproj
> ...
> -rw-r--r--  1 root  wheel   523 11 Aug 08:44 version.plist
> drwxr-xr-x  3 root  wheel    96 11 Aug 08:44 vi.lproj
> drwxr-xr-x  3 root  wheel    96 11 Aug 08:44 zh_CN.lproj
> drwxr-xr-x  3 root  wheel    96 11 Aug 08:44 zh_HK.lproj
> drwxr-xr-x  3 root  wheel    96 11 Aug 08:44 zh_TW.lproj

**Comment by kunte0** [comment]
should work now, i updated the offset for 12.5.1 
<img width="749" alt="Screenshot 2022-08-25 at 16 54 00" src="https://user-images.githubusercontent.com/33470032/186698615-53bcf50a-8e24-40db-a000-a1bdcc5d3b1d.png">

plz merge :)
